---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: rollback-sample-app
  namespace: my-apps
spec:
  serviceAccountName: default
  fetch:
  - git:
      url: https://github.com/cdelashmutt-pivotal/rollback-with-package-demo-gitops
      ref: origin/main
      subPath: rollback-sample.my-apps.vmware.com/packages
  - git:
      url: https://github.com/cdelashmutt-pivotal/rollback-with-package-demo-gitops
      ref: origin/main
      subPath: rollback-sample.my-apps.vmware.com/dev
  template:
  - ytt: {}
  deploy:
  - kapp:
      intoNs: my-apps
      rawOptions: ["--dangerous-allow-empty-list-of-resources=true"]